apiVersion: v2
name: weather-app-backend
description: >-
  The backend of Group F's weather application for the Infrastructure
  Engineering (PT) course at the Hochschule Burgenland.
type: application
version: 0.1.0
appVersion: v0.0.1
