{{- if not .Values.apiKeys.useExistingSecret }}
{{- $avwxApiKey := required "apiKeys.avwx is required when apiKeys.useExistingSecret=false" .Values.apiKeys.avwx }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "weather-app-backend.fullname" . }}
  labels:
    {{- include "weather-app-backend.labels" . | nindent 4 }}
data:
  avwx-api-key: {{ $avwxApiKey | b64enc | quote }}
{{- end }}
