{{- if not .Values.apiKeys.useExistingSecret }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "weather-app-backend.fullname" . }}
  labels:
    {{- include "weather-app-backend.labels" . | nindent 4 }}
data:
  avwx-api-key: {{ .Values.apiKeys.avwx | b64enc }}
{{- end }}
{{- if and (eq .Values.spring.profile "external-pg") (not .Values.database.useExistingSecret) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "weather-app-backend.fullname" . }}-db
  labels:
    {{- include "weather-app-backend.labels" . | nindent 4 }}
data:
  url: {{ .Values.database.url | b64enc }}
  username: {{ .Values.database.username | b64enc }}
  password: {{ .Values.database.password | b64enc }}
{{- end }}
